import datetime

WIN_WIDTH = 600
WIN_HEIGHT = 400
WIN_TITLE = "BANK"

MODES = ["Добавление", "Редактирование", "Удаление"]
CURRENT_MODE = 0

NAME_REGEX = "[А-Яа-яA-Za-z]+"
MAX_NAME_LENGTH = 255

MIN_DATE = datetime.date(1900, 1, 1)

MAX_PASSPORT_SERIES_LENGTH = 2
PASSPORT_SERIES_MASK = "[A-Za-z]+"

MAX_INFO_STRING_LENGTH = 255

HOME_PHONE_PLACEHOLDER = "xx-x-xx"
HOME_PHONE_MASK = r"\d{2}-\d-\d{2}"

MOBILE_PHONE_PLACEHOLDER = "+375..."
MOBILE_PHONE_MASK = r"\+\d{12}"
MOBILE_PHONE_LENGTH = 13
