import datetime

NAME_REGEX = "[А-Яа-яA-Za-z]+"
MAX_NAME_LENGTH = 255

MIN_DATE = datetime.date(1900, 1, 1)
DEFAULT_DATE = datetime.date(2000, 1, 1)

MAX_PASSPORT_SERIES_LENGTH = 2
PASSPORT_SERIES_MASK = "[A-Za-z]+"

MAX_INFO_STRING_LENGTH = 255

HOME_PHONE_PLACEHOLDER = "xx-x-xx"
HOME_PHONE_MASK = r"\d{2}-\d-\d{2}"

MOBILE_PHONE_PLACEHOLDER = "+375..."
MOBILE_PHONE_MASK = r"\+\d{12}"
MOBILE_PHONE_LENGTH = 13

PASSPORT_NUMBER_MASK = r"\d{7}"
PASSPORT_NUMBER_LENGTH = 7

PASSPORT_ID_MASK = r"[1-6][0-3]\d[0-1]\d{3}[ABCHKEM]\d{3}(PB|BA|BI)\d"
PASSPORT_ID_LENGTH = 14

INCOME_MASK = r"\d+(\.\d{1,2})?"
INCOME_MAX_LENGTH = 20

ID_MAX_LENGTH = 10
ID_MASK = r"\d+"


CONTRACT_NUMBER_MASK = r"\d+"
CONTRACT_NUMBER_MAX_LENGTH = 13\
