
WIN_WIDTH = 600
WIN_HEIGHT = 400
WIN_TITLE = "BANK"

MODES = ["Добавление", "Редактирование", "Удаление"]
CURRENT_MODE = 0

UI_PATH = '../window_view/window.ui'

ADD_CLIENT_TAB_INDEX = 0
CLIENT_LIST_TAB_INDEX = 1
DEPOSIT_CREATE_TAB_INDEX = 2
ACCOUNT_LIST_TAB_INDEX = 3
ADMINISTRATION_TAB_INDEX = 4
